In [1]:
import tensorflow as tf
import numpy as np

In [3]:
x = np.array([[0.0,0.0],
              [0.0,1.0],
              [1.0,0.0],
              [1.0,1.0]])

In [5]:
x

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [6]:
y = np.array([[0.0],[0.0],[0.0],[1.0]])
y

array([[0.],
       [0.],
       [0.],
       [1.]])

In [34]:
w = tf.Variable(tf.zeros([2,1], dtype=tf.float64))
type(w)

tensorflow.python.ops.variables.RefVariable

In [14]:
z = tf.Variable(tf.ones([2,1], dtype=tf.float64))
type(z)

tensorflow.python.ops.variables.RefVariable

In [18]:
print(z)

<tf.Variable 'Variable_1:0' shape=(2, 1) dtype=float64_ref>


In [29]:
def step(x):
    return tf.cast(tf.to_float(tf.math.greater_equal(x, 1)), tf.float64)

In [36]:
init = tf.global_variables_initializer()

In [37]:
camada_saida_w = tf.matmul(x,w)
camada_saida_z = tf.matmul(x,z)

In [38]:
camada_saida_ativacao = step(camada_saida_w)

In [42]:
erro = tf.subtract(y, camada_saida_ativacao)

In [46]:
delta = tf.matmul(x, erro, transpose_a=True)
treinamento = tf.assign(w, tf.add(w, tf.multiply(delta, 0.1)))

In [40]:
with tf.Session() as sess:
    sess.run(init)
    #print(sess.run(z))
    print(sess.run(camada_saida_w))
    print(sess.run(camada_saida_z))
    
    print(sess.run(tf.math.greater_equal(10, 1)))
    print(sess.run(tf.math.greater_equal(0.9, 1)))
    print(sess.run(tf.math.greater_equal(-9, 1)))
    print(sess.run(tf.to_float(tf.math.greater_equal(10, 1))))

[[0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [1.]
 [1.]
 [2.]]
True
False
False
1.0


In [51]:
with tf.Session() as sess:
    sess.run(init)
    #print(sess.run(z))
    #print(sess.run(camada_saida_w))
    #print('\n')
    #print(sess.run(camada_saida_ativacao))
    print('\n')
    #print(sess.run(erro))
    #print(sess.run(treinamento))
    epoca = 0
    for i in range(15):
        epoca += 1
        erro_total, _ = sess.run([erro, treinamento])
        erro_soma = tf.reduce_sum(erro_total)
        print(erro_total)
        print('Epoca: ', epoca, ' Erro: ', sess.run(erro_soma))
        if erro_soma.eval() == 0.0:
            break
    w_final = sess.run(w)



[[0.]
 [0.]
 [0.]
 [1.]]
Epoca:  1  Erro:  1.0
[[0.]
 [0.]
 [0.]
 [1.]]
Epoca:  2  Erro:  1.0
[[0.]
 [0.]
 [0.]
 [1.]]
Epoca:  3  Erro:  1.0
[[0.]
 [0.]
 [0.]
 [1.]]
Epoca:  4  Erro:  1.0
[[0.]
 [0.]
 [0.]
 [1.]]
Epoca:  5  Erro:  1.0
[[0.]
 [0.]
 [0.]
 [0.]]
Epoca:  6  Erro:  0.0


In [52]:
w_final

array([[0.5],
       [0.5]])

In [53]:
# teste
camada_saida_teste = tf.matmul(x, w_final)
camada_saida_ativacao_teste = step(camada_saida_teste)
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(camada_saida_ativacao_teste))

[[0.]
 [0.]
 [0.]
 [1.]]
