In [2]:
import pandas as pd
base = pd.read_csv('house-prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [4]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [5]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [6]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [7]:
base = pd.read_csv('house-prices.csv', usecols = colunas_usadas)

In [8]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

C:\Users\mario\Anaconda3\envs\Tensorflow\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [10]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [11]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [12]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [13]:
x = base.drop('price', axis = 1)
y = base.price

In [14]:
x.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [15]:
type(x)

pandas.core.frame.DataFrame

In [16]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [17]:
type(y)

pandas.core.series.Series

In [18]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [19]:
import tensorflow as tf

In [20]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [23]:
print(colunas[10])

NumericColumn(key='sqft_basement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [24]:
from sklearn.model_selection import train_test_split
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(x, y, test_size = 0.3)

In [25]:
x_treinamento.shape

(15129, 16)

In [26]:
y_treinamento.shape

(15129,)

In [27]:
x_teste.shape

(6484, 16)

In [28]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x=x_treinamento, y=y_treinamento, 
                                                         batch_size=32, num_epochs=None, shuffle=True)

In [29]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(x=x_teste, y=y_teste, 
                                                         batch_size=32, num_epochs=10000, shuffle=False)

In [ ]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

In [31]:
regressor.train(input_fn=funcao_treinamento, steps=10000)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\mario\AppData\Local\Temp\tmpef3pc1bb\model.ckpt.
INFO:tensorflow:loss = 0.23096722, step = 1
INFO:tensorflow:global_step/sec: 324.386
INFO:tensorflow:loss = 0.020286484, step = 101 (0.310 sec)
INFO:tensorflow:global_step/sec: 502.065
INFO:tensorflow:loss = 0.1842938, step = 201 (0.199 sec)
INFO:tensorflow:global_step/sec: 517.674
INFO:te

INFO:tensorflow:global_step/sec: 489.764
INFO:tensorflow:loss = 0.016080432, step = 6201 (0.204 sec)
INFO:tensorflow:global_step/sec: 517.673
INFO:tensorflow:loss = 0.018871346, step = 6301 (0.193 sec)
INFO:tensorflow:global_step/sec: 509.744
INFO:tensorflow:loss = 0.046050604, step = 6401 (0.196 sec)
INFO:tensorflow:global_step/sec: 464.706
INFO:tensorflow:loss = 0.008313809, step = 6501 (0.216 sec)
INFO:tensorflow:global_step/sec: 452.086
INFO:tensorflow:loss = 0.018194333, step = 6601 (0.222 sec)
INFO:tensorflow:global_step/sec: 497.07
INFO:tensorflow:loss = 0.008764875, step = 6701 (0.200 sec)
INFO:tensorflow:global_step/sec: 507.162
INFO:tensorflow:loss = 0.01771833, step = 6801 (0.197 sec)
INFO:tensorflow:global_step/sec: 507.162
INFO:tensorflow:loss = 0.007589827, step = 6901 (0.197 sec)
INFO:tensorflow:global_step/sec: 523.092
INFO:tensorflow:loss = 0.019199748, step = 7001 (0.191 sec)
INFO:tensorflow:global_step/sec: 492.174
INFO:tensorflow:loss = 0.0142655745, step = 7101 (0.

In [32]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-06-27T17:32:38Z
INFO:tensorflow:Graph was finalized.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from C:\Users\mario\AppData\Local\Temp\tmpef3pc1bb\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-06-27-17:32:57
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0007112353, global_step = 1

In [33]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-06-27T17:33:53Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\mario\AppData\Local\Temp\tmpef3pc1bb\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-06-27-17:34:12
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0007477979, global_step = 10000, label/mean = 0.061124623, loss = 0.023929533, prediction/mean = 0.066158
INFO:ten

In [34]:
metricas_treinamento

{'average_loss': 0.0007112353,
 'label/mean': 0.06092627,
 'loss': 0.022759529,
 'prediction/mean': 0.065409176,
 'global_step': 10000}

In [35]:
metricas_teste

{'average_loss': 0.0007477979,
 'label/mean': 0.061124623,
 'loss': 0.023929533,
 'prediction/mean': 0.066158,
 'global_step': 10000}

In [39]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x=x_teste, shuffle=False)

In [40]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [41]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\mario\AppData\Local\Temp\tmpef3pc1bb\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.10737807], dtype=float32)},
 {'predictions': array([0.1151313], dtype=float32)},
 {'predictions': array([0.00163653], dtype=float32)},
 {'predictions': array([0.13429323], dtype=float32)},
 {'predictions': array([0.12628412], dtype=float32)},
 {'predictions': array([0.05401642], dtype=float32)},
 {'predictions': array([0.07760277], dtype=float32)},
 {'predictions': array([0.0867889], dtype=float32)},
 {'predictions': array([0.08827078], dtype=float32)},
 {'predictions': array([0.0193698], dtype=float32)},
 {'predictions': array([0.02651437], dtype=float32)},
 {'predictions': array([0.03787626], dtype=float32)},
 {'predictions': array([0.08861163], dtype=float32)},
 {'predictions': array([0.11128653], dtype=float32)},
 {'predictions': array([0.04664165], dtype=float32)},
 {'predictions': array([0.06039808], dtype=float32)},
 {'predictions': array([0.07477931], dtype=float32)},
 {'predictions': array([0.01690457], dtype=float32)},
 {'predictions': array([0.05328

In [42]:
valores_previsoes = []
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\mario\AppData\Local\Temp\tmpef3pc1bb\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [43]:
valores_previsoes

[array([0.10737807], dtype=float32),
 array([0.1151313], dtype=float32),
 array([0.00163653], dtype=float32),
 array([0.13429323], dtype=float32),
 array([0.12628412], dtype=float32),
 array([0.05401642], dtype=float32),
 array([0.07760277], dtype=float32),
 array([0.0867889], dtype=float32),
 array([0.08827078], dtype=float32),
 array([0.0193698], dtype=float32),
 array([0.02651437], dtype=float32),
 array([0.03787626], dtype=float32),
 array([0.08861163], dtype=float32),
 array([0.11128653], dtype=float32),
 array([0.04664165], dtype=float32),
 array([0.06039808], dtype=float32),
 array([0.07477931], dtype=float32),
 array([0.01690457], dtype=float32),
 array([0.0532851], dtype=float32),
 array([0.12239326], dtype=float32),
 array([0.11517902], dtype=float32),
 array([0.06128477], dtype=float32),
 array([0.0129566], dtype=float32),
 array([0.09519771], dtype=float32),
 array([0.00745139], dtype=float32),
 array([0.02347094], dtype=float32),
 array([0.10067122], dtype=float32),
 array

In [44]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)

In [45]:
valores_previsoes

array([[0.10737807],
       [0.1151313 ],
       [0.00163653],
       ...,
       [0.06795023],
       [0.02816007],
       [0.03192673]], dtype=float32)

In [46]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[893757.8 ],
       [952876.1 ],
       [ 87478.52],
       ...,
       [593120.44],
       [289720.56],
       [318441.3 ]], dtype=float32)

In [47]:
y_teste

42       0.103212
20499    0.089836
12394    0.016918
2761     0.102951
13116    0.068852
4948     0.045902
9236     0.055738
14671    0.102951
9226     0.082492
12835    0.020197
9104     0.046426
18952    0.030689
10121    0.088518
5528     0.095738
12511    0.036852
12939    0.026230
10233    0.046885
767      0.024262
18486    0.028852
639      0.137049
5032     0.091803
12877    0.065574
6062     0.021639
2123     0.085311
18166    0.020328
3879     0.041311
5680     0.182951
174      0.078426
8814     0.036066
19351    0.245902
           ...   
20356    0.037370
19392    0.029046
21506    0.283789
1877     0.097705
2307     0.038578
10970    0.104000
12743    0.081311
2402     0.032459
8538     0.091148
15050    0.072525
5183     0.019016
19049    0.085246
12754    0.049180
17171    0.022951
14098    0.083934
16397    0.041967
11175    0.025836
410      0.025311
12481    0.072131
19409    0.017049
11185    0.053770
21069    0.041248
5889     0.060328
10397    0.013770
13596    0

In [48]:
y_teste.shape

(6484,)

In [50]:
y_teste2 = y_teste.values.reshape(-1,1)
y_teste2.shape

(6484, 1)

In [52]:
y_teste2 = scaler_y.inverse_transform(y_teste2)
y_teste2

array([[6.57267382e+12],
       [5.79500008e+12],
       [1.55550008e+12],
       ...,
       [4.17888132e+12],
       [2.33706258e+12],
       [3.05762508e+12]])

In [53]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [54]:
mae

4125845949419.1562