In [4]:
import pandas as pd
base = pd.read_csv('house-prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [5]:
base.shape

(21613, 21)

In [6]:
x = base.iloc[:, 5:6].values
y = base.iloc[:, 2:3].values

In [7]:
x

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]], dtype=int64)

In [8]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [9]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
x = scaler_x.fit_transform(x)
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)

C:\Users\mario\Anaconda3\envs\Tensorflow\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\mario\Anaconda3\envs\Tensorflow\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [10]:
x

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [11]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [12]:
import tensorflow as tf

In [13]:
colunas = [tf.feature_column.numeric_column('x', shape = [1])]

In [14]:
colunas

[NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [15]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\mario\\AppData\\Local\\Temp\\tmp6ll369jp', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000020773DB3A20>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [16]:
from sklearn.model_selection import train_test_split
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(x, y, test_size = 0.3)

In [17]:
x_treinamento.shape

(15129, 1)

In [18]:
x_teste.shape

(6484, 1)

In [19]:
y_treinamento.shape

(15129, 1)

In [20]:
y_teste.shape

(6484, 1)

In [23]:
funcao_treinamento = tf.estimator.inputs.numpy_input_fn({'x':x_treinamento}, y_treinamento, batch_size=32, num_epochs=None, shuffle=True)

In [24]:
funcao_teste = tf.estimator.inputs.numpy_input_fn({'x': x_teste}, y_teste, batch_size=32, num_epochs=1000, shuffle=False)

In [25]:
regressor.train(input_fn=funcao_treinamento, steps=10000)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\mario\AppData\Local\Temp\tmp6ll369jp\model.ckpt.
INFO:tensorflow:loss = 77.12207, step = 1
INFO:tensorflow:global_step/sec: 1332.13
INFO:tensorflow:loss = 9.143672, step = 101 (0.076 sec)
INFO:tensorflow:global_step/sec: 1998.21
INFO:tensorflow:loss = 10.340281, step = 201 (0.049 sec)
INFO:tensorflow:global_step/sec: 2171.99
INFO:tensorflow:loss = 11.544031, step = 301 (0.047 sec)
INFO:tensorflow:global_step

INFO:tensorflow:global_step/sec: 1959.02
INFO:tensorflow:loss = 8.741579, step = 6601 (0.051 sec)
INFO:tensorflow:global_step/sec: 1998.2
INFO:tensorflow:loss = 13.824682, step = 6701 (0.050 sec)
INFO:tensorflow:global_step/sec: 2081.51
INFO:tensorflow:loss = 8.780927, step = 6801 (0.048 sec)
INFO:tensorflow:global_step/sec: 2220.2
INFO:tensorflow:loss = 17.393559, step = 6901 (0.045 sec)
INFO:tensorflow:global_step/sec: 1998.23
INFO:tensorflow:loss = 93.302574, step = 7001 (0.049 sec)
INFO:tensorflow:global_step/sec: 2220.23
INFO:tensorflow:loss = 10.869734, step = 7101 (0.045 sec)
INFO:tensorflow:global_step/sec: 2125.75
INFO:tensorflow:loss = 12.084881, step = 7201 (0.047 sec)
INFO:tensorflow:global_step/sec: 1959.05
INFO:tensorflow:loss = 15.41306, step = 7301 (0.051 sec)
INFO:tensorflow:global_step/sec: 2220.23
INFO:tensorflow:loss = 5.0811315, step = 7401 (0.046 sec)
INFO:tensorflow:global_step/sec: 2081.49
INFO:tensorflow:loss = 8.532501, step = 7501 (0.047 sec)
INFO:tensorflow:

In [26]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-05-27T01:06:05Z
INFO:tensorflow:Graph was finalized.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from C:\Users\mario\AppData\Local\Temp\tmp6ll369jp\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-05-27-01:06:09
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.49902323, global_step = 100

In [27]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-05-27T01:07:05Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\mario\AppData\Local\Temp\tmp6ll369jp\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-05-27-01:07:10
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.52820754, global_step = 10000, label/mean = -0.0016488514, loss = 16.902641, prediction/mean = -0.0044029304
INFO:

In [28]:
metricas_treinamento

{'average_loss': 0.49902323,
 'label/mean': 0.0007636975,
 'loss': 15.968743,
 'prediction/mean': 0.0020828098,
 'global_step': 10000}

In [29]:
metricas_teste

{'average_loss': 0.52820754,
 'label/mean': -0.0016488514,
 'loss': 16.902641,
 'prediction/mean': -0.0044029304,
 'global_step': 10000}

In [30]:
import numpy as np

In [32]:
novas_casas = np.array([[800],[900],[1000]])
novas_casas

array([[ 800],
       [ 900],
       [1000]])

In [33]:
novas_casas = scaler_x.transform(novas_casas)
novas_casas

C:\Users\mario\Anaconda3\envs\Tensorflow\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.39358923],
       [-1.28470655],
       [-1.17582386]])

In [34]:
funcao_preovisao = tf.estimator.inputs.numpy_input_fn({'x':novas_casas},shuffle=False)

In [35]:
previsoes = regressor.predict(input_fn=funcao_preovisao)

In [36]:
previsoes

<generator object EstimatorV2.predict at 0x000002077A6E0780>

In [37]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\mario\AppData\Local\Temp\tmp6ll369jp\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([-0.95396197], dtype=float32)},
 {'predictions': array([-0.8794168], dtype=float32)},
 {'predictions': array([-0.80487156], dtype=float32)}]

In [39]:
for p in regressor.predict(input_fn=funcao_preovisao):
    print(scaler_y.inverse_transform(p['predictions']))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\mario\AppData\Local\Temp\tmp6ll369jp\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[189870.86]
[217237.77]
[244604.73]
